# Generated by Django 4.0.5 on 2022-08-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajes',
            name='descripcion',
            field=models.CharField(default=22, max_length=300),
            preserve_default=False,
        ),
    ]
