# Generated by Django 4.0.5 on 2022-08-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_hotel_paquete_vuelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Vuelo',
        ),
    ]
