# Generated by Django 4.0.5 on 2022-08-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_delete_hotel_delete_paquete_delete_vuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('date_departue', models.DateField(auto_now_add=True, null=True)),
                ('date_return', models.DateField(auto_now_add=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departure', models.TextField()),
                ('destination', models.TextField()),
                ('date_departue', models.DateField(auto_now_add=True, null=True)),
                ('date_return', models.DateField(auto_now_add=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
